# -*- coding: utf-8 -*-
"""Proyecto Python Matthias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JIoyEU212q7_ZUeSS3JlVYQAkpIGqhcM
"""

import pandas as pd
import os

df = pd.read_csv('/content/drive/MyDrive/export.csv', sep=";")

def convertir_numero(numero):
    numero = numero.replace(',', '.')

    partes = numero.split('.')

    if len(partes) == 2:
        decimales = partes[1]
        if len(decimales) == 1:
            decimales += '0'
        numero = partes[0] + '.' + decimales
    elif len(partes) == 1:
        numero += '.00'

    return numero

df['Netto-Einkaufspreis (indiv., falls vorh.)'] =\
 df['Netto-Einkaufspreis (indiv., falls vorh.)'].apply(convertir_numero)

df['Katalogpreis / empf. VK - VK Brutto Preis ./. Rabatt'] =\
 df['Katalogpreis / empf. VK - VK Brutto Preis ./. Rabatt'].apply(convertir_numero)

df['Gebindemenge / BMEcat Verpackungsmenge'] =\
 df['Gebindemenge / BMEcat Verpackungsmenge'].astype(str).str.split(',').str[0]

from datetime import date

df['Preisdatum EK / Konditionsdatum'] = date.today()

df = df.astype(str).apply(lambda x: x.str.rjust(20))

df['Netto-Einkaufspreis (indiv., falls vorh.)'] =\
 df['Netto-Einkaufspreis (indiv., falls vorh.)'].astype(float).apply(lambda x: f"{x:.2f}".replace(".", ""))
df['Netto-Einkaufspreis (indiv., falls vorh.)'] =\
 df['Netto-Einkaufspreis (indiv., falls vorh.)'].apply(lambda x: f"{x[:2]}.{x[2:]}")

df['Katalogpreis / empf. VK - VK Brutto Preis ./. Rabatt'] =\
 df['Katalogpreis / empf. VK - VK Brutto Preis ./. Rabatt'].astype(float).apply(lambda x: f"{x:.2f}".replace(".", ""))
df['Katalogpreis / empf. VK - VK Brutto Preis ./. Rabatt'] =\
 df['Katalogpreis / empf. VK - VK Brutto Preis ./. Rabatt'].apply(lambda x: f"{x[:2]}.{x[2:]}")


# splitting max 15000 rows
# cuando ya tienes 15000 rows (export_1.csv)
# otro export nuevo (export_2.csv)
# hasta todos rows


"""#Listo ✅

"""

df.to_csv('/content/drive/MyDrive/export_tercera_revision.csv', index= False)