# -*- coding: utf-8 -*-
"""Proyecto Python Matthias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JIoyEU212q7_ZUeSS3JlVYQAkpIGqhcM
"""

import pandas as pd
import os

df = pd.read_csv('https://github.com/GuillermoK1/Matthias/blob/main/import/export.csv', sep=";")

def convertir_numero(numero):
    numero = numero.replace(',', '.')

    partes = numero.split('.')

    if len(partes) == 2:
        decimales = partes[1]
        if len(decimales) == 1:
            decimales += '0'
        numero = partes[0] + '.' + decimales
    elif len(partes) == 1:
        numero += '.00'

    return numero

df['Netto-Einkaufspreis (indiv., falls vorh.)'] =\
 df['Netto-Einkaufspreis (indiv., falls vorh.)'].apply(convertir_numero)

df['Katalogpreis / empf. VK - VK Brutto Preis ./. Rabatt'] =\
 df['Katalogpreis / empf. VK - VK Brutto Preis ./. Rabatt'].apply(convertir_numero)

df['Gebindemenge / BMEcat Verpackungsmenge'] =\
 df['Gebindemenge / BMEcat Verpackungsmenge'].astype(str).str.split(',').str[0]

from datetime import date

df['Preisdatum EK / Konditionsdatum'] = date.today()

df = df.astype(str).apply(lambda x: x.str.rjust(20))

"""#Listo ✅

"""

# splitting max 15000 rows
# cuando ya tienes 15000 rows (export_1.csv)
# otro export nuevo (export_2.csv)
# hasta todos rows
def dividir_y_exportar_dataframe(df, ruta_carpeta, num_filas=15000):
    num_archivos = len(df) // num_filas + 1
    for i in range(num_archivos):
        carpeta = os.path.join(ruta_carpeta, f'export_{i+1}')
        os.makedirs(carpeta, exist_ok=True)
        archivo_export = os.path.join(carpeta, 'archivo.csv')
        df[i*num_filas:(i+1)*num_filas].to_csv(archivo_export, index=False)

#Modificar nombre de ruta_carpeta aquí abajo.
dividir_y_exportar_dataframe(df, 'https://github.com/GuillermoK1/Matthias/blob/main/import/export.csv')